export const PathName = {
  Home: '/',
  WhatWeOffer: '#',
  Sellers: '#',
  ConnectUs: '#',
  Telegram: '#',
  Twitter: '#',
  Facebook: '#',
  LinkedIn: '#',
  Instagram: '#',
  Youtube: '#',
  GooglePlay: '#',
  AppStore: '#',
  MacOS: '#',
  Web: '#',
  Windows: '#',
};
