export const PathName = {
  Home: '/',
  HomeFooter: '/legal_information',
  SignIn: '/sign-in',
  Registration: '/signup',
  ForgotPassword: '/forgot-password',

  Cabinet: '/cabinet',
  Profile: '/cabinet/profile',
  Partner: '/cabinet/partner',
  Status: '/cabinet/status',
  Pool: '/cabinet/pool',
  Instruments: '/cabinet/instruments',
  Transactions: '/cabinet/transactions',
  Support: '/cabinet/support',
  SupportMyTickets: '/cabinet/support/my-tickets',
  ItemId: ':id',
  News: '/cabinet/news',
  NewsItem: '/cabinet/news/new',

  WhatWeOffer: 'what-we-offer',
  Sellers: 'sellers',
  ConnectUs: 'connect-with-us',
  Telegram: 'https://t.me/globalhubeclipse',
  Twitter: 'https://twitter.com/ghubeclipse',
  Facebook: 'https://www.facebook.com/profile.php?id=61555251314245',
  LinkedIn: 'https://www.linkedin.com/in/globalhubeclipse/',
  Instagram: 'https://www.instagram.com/eclipse_global_hub?igsh=MXBxcHNhZmZzN2VkbA%3D%3D&utm_source=qr',
  Youtube: 'https://www.youtube.com/@GLOBALHUBECLIPSE',
  GooglePlay: '#',
  AppStore: '#',
  MacOS: '#',
  Web: '#',
  Windows: '#',
};
